import Head from 'next/head'
import Image from 'next/image'
import GetStarted from '../components/GetStarted'
import Hero from '../components/Hero'
import HomeContent from '../components/HomeContent'
import { ToastContainer } from 'react-toastify';
// import Popup from '../components/Popup'


export default function Home() {
  return (
    <div>
      <ToastContainer  limit={3}/>
      {/* <Popup /> */}
      <Hero />
      <HomeContent />
      <GetStarted />
    </div>
  )
}

{/* <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div> */}